module.exports = {
	apps: [
		{
			name: "candle-save",
			script: "./src/services/candle-save/index.ts",
			instances: 1,
			exec_mode: "fork",
			watch: false,
			autorestart: false,
			max_restarts: 1,
			env: {
				TZ: "Asia/Seoul",
			},
			merge_logs: true,
			error_file: "logs/candle-save-error.log",
			out_file: "logs/candle-save-out.log",
		},
		{
			name: "analysis",
			script: "./src/services/analysis/index.ts",
			instances: 1,
			exec_mode: "fork",
			watch: true,
			max_memory_restart: "300M",
			env: {
				NODE_ENV: "production",
				TZ: "Asia/Seoul",
			},
			exp_backoff_restart_delay: 100,
			group: "analysis",
		},
		{
			name: "trading",
			script: "./src/services/trading/index.ts",
			instances: 1,
			exec_mode: "fork",
			watch: true,
			max_memory_restart: "250M",
			env: {
				NODE_ENV: "production",
				TZ: "Asia/Seoul",
			},
			max_restarts: 3,
			group: "trading",
		},
		{
			name: "account",
			script: "./src/services/account/index.ts",
			instances: 1,
			exec_mode: "fork",
			watch: true,
			max_memory_restart: "200M",
			env: {
				NODE_ENV: "production",
				TZ: "Asia/Seoul",
			},
			cron_restart: "0 0 * * *",
			group: "account",
		},
	],
	post_update: ["npm install"],
	watch: ["src/pm2-events.ts"],
	ignore_watch: ["node_modules", "logs"],
	instance_var: "INSTANCE_ID",
	pmx: true,
};
